"""initial_schema

Revision ID: 2265fadb4d83
Revises: 
Create Date: 2026-06-12 10:08:07.069900

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2265fadb4d83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('meal_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_registry',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('pnr', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('ffp_tier', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pnr')
    )
    op.create_table('crew_members',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('airline_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_zone', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('flights',
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('dep_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arr_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('load_factor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_items',
    sa.Column('meal_code', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cuisine_type', sa.String(length=100), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergen_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dietary_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('meal_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['meal_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_code')
    )
    op.create_index('ix_meal_items_allergen_gin', 'meal_items', ['allergen_flags'], unique=False, postgresql_using='gin')
    op.create_table('passenger_profiles',
    sa.Column('passenger_id', sa.Uuid(), nullable=False),
    sa.Column('dietary_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergy_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cuisine_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portion_pref', sa.String(length=20), nullable=True),
    sa.Column('price_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('preference_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passenger_id')
    )
    op.create_table('flight_inventory',
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('initial_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('served_qty', sa.Integer(), nullable=False),
    sa.Column('wasted_qty', sa.Integer(), nullable=False),
    sa.Column('restock_alert_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('initial_qty >= 0', name='ck_inventory_initial_non_negative'),
    sa.CheckConstraint('reserved_qty + served_qty <= initial_qty', name='ck_inventory_not_overreserved'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_inventory_reserved_non_negative'),
    sa.CheckConstraint('served_qty >= 0', name='ck_inventory_served_non_negative'),
    sa.CheckConstraint('wasted_qty >= 0', name='ck_inventory_wasted_non_negative'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_inventory_available', 'flight_inventory', ['flight_id'], unique=False, postgresql_where=sa.text('initial_qty - reserved_qty - served_qty > 0'))
    op.create_table('flight_seats',
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passenger_orders',
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('passenger_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('assigned_crew_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_crew_id'], ['crew_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passenger_orders_status', 'passenger_orders', ['status'], unique=False)
    op.create_table('delivery_tasks',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('crew_id', sa.Uuid(), nullable=True),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('route_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crew_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['passenger_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('feedback',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('taste_rating', sa.Integer(), nullable=True),
    sa.Column('temp_rating', sa.Integer(), nullable=True),
    sa.Column('portion_rating', sa.Integer(), nullable=True),
    sa.Column('speed_rating', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['passenger_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('customisations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['passenger_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('feedback')
    op.drop_table('delivery_tasks')
    op.drop_index('ix_passenger_orders_status', table_name='passenger_orders')
    op.drop_table('passenger_orders')
    op.drop_table('flight_seats')
    op.drop_index('ix_flight_inventory_available', table_name='flight_inventory', postgresql_where=sa.text('initial_qty - reserved_qty - served_qty > 0'))
    op.drop_table('flight_inventory')
    op.drop_table('passenger_profiles')
    op.drop_index('ix_meal_items_allergen_gin', table_name='meal_items', postgresql_using='gin')
    op.drop_table('meal_items')
    op.drop_table('flights')
    op.drop_table('crew_members')
    op.drop_table('passengers')
    op.drop_table('model_registry')
    op.drop_table('meal_categories')
    op.drop_table('airlines')
    # ### end Alembic commands ###
