"""add passenger priority attributes

Revision ID: 2fa5ffe6890b
Revises: 2265fadb4d83
Create Date: 2026-06-19 15:51:06.755799

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2fa5ffe6890b'
down_revision: Union[str, None] = '2265fadb4d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('is_medical', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('passengers', sa.Column('has_infant', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('passengers', sa.Column('is_connecting', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'is_connecting')
    op.drop_column('passengers', 'has_infant')
    op.drop_column('passengers', 'is_medical')
    # ### end Alembic commands ###
