"""add waste_interventions table

Revision ID: 3b04ce350a68
Revises: b9df830d52fe
Create Date: 2026-06-20 18:10:02.874034

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3b04ce350a68'
down_revision: Union[str, None] = 'b9df830d52fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_interventions',
    sa.Column('flight_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'meal_id', 'cabin_class', name='uq_waste_intervention_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_interventions')
    # ### end Alembic commands ###
