"""add is_alcohol to meal_items

Revision ID: b9df830d52fe
Revises: 2fa5ffe6890b
Create Date: 2026-06-19 16:08:40.673296

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b9df830d52fe'
down_revision: Union[str, None] = '2fa5ffe6890b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_items', sa.Column('is_alcohol', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_items', 'is_alcohol')
    # ### end Alembic commands ###
